# log config
logging:
  level:
    ROOT: INFO

# brpc config
brpc:
  global:
    naming:
      version: 1.0.0
      ignoreFailOfNamingService: true
    server:
      port: 8228
      workThreadNum: 1
      ioThreadNum: 1