/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.baidu.cie.superarchive.v2.web.identify;

public class ConnectDocInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ConnectDocInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConnectDocInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SearchDocModuleJNI.delete_ConnectDocInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDoc_id(long value) {
    SearchDocModuleJNI.ConnectDocInfo_doc_id_set(swigCPtr, this, value);
  }

  public long getDoc_id() {
    return SearchDocModuleJNI.ConnectDocInfo_doc_id_get(swigCPtr, this);
  }

  public void setDoc_type(long value) {
    SearchDocModuleJNI.ConnectDocInfo_doc_type_set(swigCPtr, this, value);
  }

  public long getDoc_type() {
    return SearchDocModuleJNI.ConnectDocInfo_doc_type_get(swigCPtr, this);
  }

  public ConnectDocInfo() {
    this(SearchDocModuleJNI.new_ConnectDocInfo(), true);
  }

}
