/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.baidu.cie.superarchive.v2.web.identify;

public class ConnectPair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ConnectPair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConnectPair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SearchDocModuleJNI.delete_ConnectPair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDoc_x(ConnectDocInfo value) {
    SearchDocModuleJNI.ConnectPair_doc_x_set(swigCPtr, this, ConnectDocInfo.getCPtr(value), value);
  }

  public ConnectDocInfo getDoc_x() {
    long cPtr = SearchDocModuleJNI.ConnectPair_doc_x_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ConnectDocInfo(cPtr, false);
  }

  public void setDoc_y(ConnectDocInfo value) {
    SearchDocModuleJNI.ConnectPair_doc_y_set(swigCPtr, this, ConnectDocInfo.getCPtr(value), value);
  }

  public ConnectDocInfo getDoc_y() {
    long cPtr = SearchDocModuleJNI.ConnectPair_doc_y_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ConnectDocInfo(cPtr, false);
  }

  public ConnectPair() {
    this(SearchDocModuleJNI.new_ConnectPair(), true);
  }

}
