/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.baidu.cie.superarchive.v2.web.identify;

public class Document {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Document(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Document obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SearchDocModuleJNI.delete_Document(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDoc_id(long value) {
    SearchDocModuleJNI.Document_doc_id_set(swigCPtr, this, value);
  }

  public long getDoc_id() {
    return SearchDocModuleJNI.Document_doc_id_get(swigCPtr, this);
  }

  public void setVision_clusters(VecCluster value) {
    SearchDocModuleJNI.Document_vision_clusters_set(swigCPtr, this, VecCluster.getCPtr(value), value);
  }

  public VecCluster getVision_clusters() {
    long cPtr = SearchDocModuleJNI.Document_vision_clusters_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VecCluster(cPtr, false);
  }

  public void setCamera_id_count(UnorderedMapIntInt value) {
    SearchDocModuleJNI.Document_camera_id_count_set(swigCPtr, this, UnorderedMapIntInt.getCPtr(value), value);
  }

  public UnorderedMapIntInt getCamera_id_count() {
    long cPtr = SearchDocModuleJNI.Document_camera_id_count_get(swigCPtr, this);
    return (cPtr == 0) ? null : new UnorderedMapIntInt(cPtr, false);
  }

  public void setCamera_names_count(UnorderedMapStringInt value) {
    SearchDocModuleJNI.Document_camera_names_count_set(swigCPtr, this, UnorderedMapStringInt.getCPtr(value), value);
  }

  public UnorderedMapStringInt getCamera_names_count() {
    long cPtr = SearchDocModuleJNI.Document_camera_names_count_get(swigCPtr, this);
    return (cPtr == 0) ? null : new UnorderedMapStringInt(cPtr, false);
  }

  public void setGeohash_count(UnorderedMapStringInt value) {
    SearchDocModuleJNI.Document_geohash_count_set(swigCPtr, this, UnorderedMapStringInt.getCPtr(value), value);
  }

  public UnorderedMapStringInt getGeohash_count() {
    long cPtr = SearchDocModuleJNI.Document_geohash_count_get(swigCPtr, this);
    return (cPtr == 0) ? null : new UnorderedMapStringInt(cPtr, false);
  }

  public void setStay_time_count(UnorderedMapStringInt value) {
    SearchDocModuleJNI.Document_stay_time_count_set(swigCPtr, this, UnorderedMapStringInt.getCPtr(value), value);
  }

  public UnorderedMapStringInt getStay_time_count() {
    long cPtr = SearchDocModuleJNI.Document_stay_time_count_get(swigCPtr, this);
    return (cPtr == 0) ? null : new UnorderedMapStringInt(cPtr, false);
  }

  public void setAge_type(UnorderedMapIntInt value) {
    SearchDocModuleJNI.Document_age_type_set(swigCPtr, this, UnorderedMapIntInt.getCPtr(value), value);
  }

  public UnorderedMapIntInt getAge_type() {
    long cPtr = SearchDocModuleJNI.Document_age_type_get(swigCPtr, this);
    return (cPtr == 0) ? null : new UnorderedMapIntInt(cPtr, false);
  }

  public void setCar_plate_count(UnorderedMapStringInt value) {
    SearchDocModuleJNI.Document_car_plate_count_set(swigCPtr, this, UnorderedMapStringInt.getCPtr(value), value);
  }

  public UnorderedMapStringInt getCar_plate_count() {
    long cPtr = SearchDocModuleJNI.Document_car_plate_count_get(swigCPtr, this);
    return (cPtr == 0) ? null : new UnorderedMapStringInt(cPtr, false);
  }

  public void setNum_pictures(int value) {
    SearchDocModuleJNI.Document_num_pictures_set(swigCPtr, this, value);
  }

  public int getNum_pictures() {
    return SearchDocModuleJNI.Document_num_pictures_get(swigCPtr, this);
  }

  public void setMask_num(int value) {
    SearchDocModuleJNI.Document_mask_num_set(swigCPtr, this, value);
  }

  public int getMask_num() {
    return SearchDocModuleJNI.Document_mask_num_get(swigCPtr, this);
  }

  public void setRep_pic_id(VecUnsignedLongLong value) {
    SearchDocModuleJNI.Document_rep_pic_id_set(swigCPtr, this, VecUnsignedLongLong.getCPtr(value), value);
  }

  public VecUnsignedLongLong getRep_pic_id() {
    long cPtr = SearchDocModuleJNI.Document_rep_pic_id_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VecUnsignedLongLong(cPtr, false);
  }

  public void setReal_doc_id(VecLongLong value) {
    SearchDocModuleJNI.Document_real_doc_id_set(swigCPtr, this, VecLongLong.getCPtr(value), value);
  }

  public VecLongLong getReal_doc_id() {
    long cPtr = SearchDocModuleJNI.Document_real_doc_id_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VecLongLong(cPtr, false);
  }

  public void setDoc_title_id(long value) {
    SearchDocModuleJNI.Document_doc_title_id_set(swigCPtr, this, value);
  }

  public long getDoc_title_id() {
    return SearchDocModuleJNI.Document_doc_title_id_get(swigCPtr, this);
  }

  public void setDb_type(int value) {
    SearchDocModuleJNI.Document_db_type_set(swigCPtr, this, value);
  }

  public int getDb_type() {
    return SearchDocModuleJNI.Document_db_type_get(swigCPtr, this);
  }

  public Document() {
    this(SearchDocModuleJNI.new_Document(), true);
  }

}
