/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.baidu.cie.superarchive.v2.web.identify;

public class ImageSearchDoc {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ImageSearchDoc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImageSearchDoc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SearchDocModuleJNI.delete_ImageSearchDoc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ImageSearchDoc() {
    this(SearchDocModuleJNI.new_ImageSearchDoc(), true);
  }

  public boolean search_doc(Vecfloat query_vec, int topk, double min_score, UnorderedMapLongLongDocument query_doc_dicts) {
    return SearchDocModuleJNI
            .ImageSearchDoc_search_doc__SWIG_0(swigCPtr, this, Vecfloat.getCPtr(query_vec), query_vec, topk,
                    min_score, UnorderedMapLongLongDocument
                    .getCPtr(query_doc_dicts), query_doc_dicts);
  }

  public boolean search_doc(long doc_id, int db_type, UnorderedMapLongLongDocument query_doc_dict) {
    return SearchDocModuleJNI
            .ImageSearchDoc_search_doc__SWIG_1(swigCPtr, this, doc_id, db_type, UnorderedMapLongLongDocument.getCPtr(query_doc_dict), query_doc_dict);
  }

  public boolean init_search_instance(TaskContext task_context, UnorderedMapStringString conf_dict) {
    return SearchDocModuleJNI
            .ImageSearchDoc_init_search_instance(swigCPtr, this, TaskContext.getCPtr(task_context), task_context, UnorderedMapStringString
                    .getCPtr(conf_dict), conf_dict);
  }

}
