/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.baidu.cie.superarchive.v2.web.identify;

public class PairFeature {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PairFeature(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PairFeature obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SearchDocModuleJNI.delete_PairFeature(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFace_sim(float value) {
    SearchDocModuleJNI.PairFeature_face_sim_set(swigCPtr, this, value);
  }

  public float getFace_sim() {
    return SearchDocModuleJNI.PairFeature_face_sim_get(swigCPtr, this);
  }

  public void setAgetype_x(int value) {
    SearchDocModuleJNI.PairFeature_agetype_x_set(swigCPtr, this, value);
  }

  public int getAgetype_x() {
    return SearchDocModuleJNI.PairFeature_agetype_x_get(swigCPtr, this);
  }

  public void setAgetype_y(int value) {
    SearchDocModuleJNI.PairFeature_agetype_y_set(swigCPtr, this, value);
  }

  public int getAgetype_y() {
    return SearchDocModuleJNI.PairFeature_agetype_y_get(swigCPtr, this);
  }

  public void setBlur_x(float value) {
    SearchDocModuleJNI.PairFeature_blur_x_set(swigCPtr, this, value);
  }

  public float getBlur_x() {
    return SearchDocModuleJNI.PairFeature_blur_x_get(swigCPtr, this);
  }

  public void setBlur_y(float value) {
    SearchDocModuleJNI.PairFeature_blur_y_set(swigCPtr, this, value);
  }

  public float getBlur_y() {
    return SearchDocModuleJNI.PairFeature_blur_y_get(swigCPtr, this);
  }

  public void setMask_x(int value) {
    SearchDocModuleJNI.PairFeature_mask_x_set(swigCPtr, this, value);
  }

  public int getMask_x() {
    return SearchDocModuleJNI.PairFeature_mask_x_get(swigCPtr, this);
  }

  public void setMask_y(int value) {
    SearchDocModuleJNI.PairFeature_mask_y_set(swigCPtr, this, value);
  }

  public int getMask_y() {
    return SearchDocModuleJNI.PairFeature_mask_y_get(swigCPtr, this);
  }

  public void setScore_x(float value) {
    SearchDocModuleJNI.PairFeature_score_x_set(swigCPtr, this, value);
  }

  public float getScore_x() {
    return SearchDocModuleJNI.PairFeature_score_x_get(swigCPtr, this);
  }

  public void setScore_y(float value) {
    SearchDocModuleJNI.PairFeature_score_y_set(swigCPtr, this, value);
  }

  public float getScore_y() {
    return SearchDocModuleJNI.PairFeature_score_y_get(swigCPtr, this);
  }

  public void setEyeocc_x(float value) {
    SearchDocModuleJNI.PairFeature_eyeocc_x_set(swigCPtr, this, value);
  }

  public float getEyeocc_x() {
    return SearchDocModuleJNI.PairFeature_eyeocc_x_get(swigCPtr, this);
  }

  public void setEyeocc_y(float value) {
    SearchDocModuleJNI.PairFeature_eyeocc_y_set(swigCPtr, this, value);
  }

  public float getEyeocc_y() {
    return SearchDocModuleJNI.PairFeature_eyeocc_y_get(swigCPtr, this);
  }

  public void setDistance(float value) {
    SearchDocModuleJNI.PairFeature_distance_set(swigCPtr, this, value);
  }

  public float getDistance() {
    return SearchDocModuleJNI.PairFeature_distance_get(swigCPtr, this);
  }

  public void setCar_dist(int value) {
    SearchDocModuleJNI.PairFeature_car_dist_set(swigCPtr, this, value);
  }

  public int getCar_dist() {
    return SearchDocModuleJNI.PairFeature_car_dist_get(swigCPtr, this);
  }

  public void setTime(int value) {
    SearchDocModuleJNI.PairFeature_time_set(swigCPtr, this, value);
  }

  public int getTime() {
    return SearchDocModuleJNI.PairFeature_time_get(swigCPtr, this);
  }

  public PairFeature() {
    this(SearchDocModuleJNI.new_PairFeature(), true);
  }

}
