/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.baidu.cie.superarchive.v2.web.identify;

public class Pair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Pair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Pair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SearchDocModuleJNI.delete_Pair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId_x(java.math.BigInteger value) {
    SearchDocModuleJNI.Pair_id_x_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getId_x() {
    return SearchDocModuleJNI.Pair_id_x_get(swigCPtr, this);
  }

  public void setId_y(java.math.BigInteger value) {
    SearchDocModuleJNI.Pair_id_y_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getId_y() {
    return SearchDocModuleJNI.Pair_id_y_get(swigCPtr, this);
  }

  public void setScore(float value) {
    SearchDocModuleJNI.Pair_score_set(swigCPtr, this, value);
  }

  public float getScore() {
    return SearchDocModuleJNI.Pair_score_get(swigCPtr, this);
  }

  public Pair() {
    this(SearchDocModuleJNI.new_Pair(), true);
  }

}
