/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.baidu.cie.superarchive.v2.web.identify;

public class Picture {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Picture(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Picture obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SearchDocModuleJNI.delete_Picture(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPic_id(java.math.BigInteger value) {
    SearchDocModuleJNI.Picture_pic_id_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getPic_id() {
    return SearchDocModuleJNI.Picture_pic_id_get(swigCPtr, this);
  }

  public void setFeature(Vecfloat value) {
    SearchDocModuleJNI.Picture_feature_set(swigCPtr, this, Vecfloat.getCPtr(value), value);
  }

  public Vecfloat getFeature() {
    long cPtr = SearchDocModuleJNI.Picture_feature_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Vecfloat(cPtr, false);
  }

  public void setCamera_id(int value) {
    SearchDocModuleJNI.Picture_camera_id_set(swigCPtr, this, value);
  }

  public int getCamera_id() {
    return SearchDocModuleJNI.Picture_camera_id_get(swigCPtr, this);
  }

  public void setLongitude(float value) {
    SearchDocModuleJNI.Picture_longitude_set(swigCPtr, this, value);
  }

  public float getLongitude() {
    return SearchDocModuleJNI.Picture_longitude_get(swigCPtr, this);
  }

  public void setLatitude(float value) {
    SearchDocModuleJNI.Picture_latitude_set(swigCPtr, this, value);
  }

  public float getLatitude() {
    return SearchDocModuleJNI.Picture_latitude_get(swigCPtr, this);
  }

  public void setCamera_name(String value) {
    SearchDocModuleJNI.Picture_camera_name_set(swigCPtr, this, value);
  }

  public String getCamera_name() {
    return SearchDocModuleJNI.Picture_camera_name_get(swigCPtr, this);
  }

  public void setSnapshot_time(java.math.BigInteger value) {
    SearchDocModuleJNI.Picture_snapshot_time_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getSnapshot_time() {
    return SearchDocModuleJNI.Picture_snapshot_time_get(swigCPtr, this);
  }

  public void setCar_plate(String value) {
    SearchDocModuleJNI.Picture_car_plate_set(swigCPtr, this, value);
  }

  public String getCar_plate() {
    return SearchDocModuleJNI.Picture_car_plate_get(swigCPtr, this);
  }

  public void setFace_score(float value) {
    SearchDocModuleJNI.Picture_face_score_set(swigCPtr, this, value);
  }

  public float getFace_score() {
    return SearchDocModuleJNI.Picture_face_score_get(swigCPtr, this);
  }

  public void setBlur(float value) {
    SearchDocModuleJNI.Picture_blur_set(swigCPtr, this, value);
  }

  public float getBlur() {
    return SearchDocModuleJNI.Picture_blur_get(swigCPtr, this);
  }

  public void setAge_type(int value) {
    SearchDocModuleJNI.Picture_age_type_set(swigCPtr, this, value);
  }

  public int getAge_type() {
    return SearchDocModuleJNI.Picture_age_type_get(swigCPtr, this);
  }

  public void setOcclu(Vecfloat value) {
    SearchDocModuleJNI.Picture_occlu_set(swigCPtr, this, Vecfloat.getCPtr(value), value);
  }

  public Vecfloat getOcclu() {
    long cPtr = SearchDocModuleJNI.Picture_occlu_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Vecfloat(cPtr, false);
  }

  public void setMain_driver(int value) {
    SearchDocModuleJNI.Picture_main_driver_set(swigCPtr, this, value);
  }

  public int getMain_driver() {
    return SearchDocModuleJNI.Picture_main_driver_get(swigCPtr, this);
  }

  public void setFacemask(int value) {
    SearchDocModuleJNI.Picture_facemask_set(swigCPtr, this, value);
  }

  public int getFacemask() {
    return SearchDocModuleJNI.Picture_facemask_get(swigCPtr, this);
  }

  public void setCamera_tag(int value) {
    SearchDocModuleJNI.Picture_camera_tag_set(swigCPtr, this, value);
  }

  public int getCamera_tag() {
    return SearchDocModuleJNI.Picture_camera_tag_get(swigCPtr, this);
  }

  public void setFacemask_prob(float value) {
    SearchDocModuleJNI.Picture_facemask_prob_set(swigCPtr, this, value);
  }

  public float getFacemask_prob() {
    return SearchDocModuleJNI.Picture_facemask_prob_get(swigCPtr, this);
  }

  public Picture() {
    this(SearchDocModuleJNI.new_Picture(), true);
  }

}
