/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.baidu.cie.superarchive.v2.web.identify;

public class QueryResult {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected QueryResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(QueryResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SearchDocModuleJNI.delete_QueryResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setQuery_id(long value) {
    SearchDocModuleJNI.QueryResult_query_id_set(swigCPtr, this, value);
  }

  public long getQuery_id() {
    return SearchDocModuleJNI.QueryResult_query_id_get(swigCPtr, this);
  }

  public void setScores(Vecfloat value) {
    SearchDocModuleJNI.QueryResult_scores_set(swigCPtr, this, Vecfloat.getCPtr(value), value);
  }

  public Vecfloat getScores() {
    long cPtr = SearchDocModuleJNI.QueryResult_scores_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Vecfloat(cPtr, false);
  }

  public void setDoc_ids(VecLongLong value) {
    SearchDocModuleJNI.QueryResult_doc_ids_set(swigCPtr, this, VecLongLong.getCPtr(value), value);
  }

  public VecLongLong getDoc_ids() {
    long cPtr = SearchDocModuleJNI.QueryResult_doc_ids_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VecLongLong(cPtr, false);
  }

  public QueryResult() {
    this(SearchDocModuleJNI.new_QueryResult(), true);
  }

}
