/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.baidu.cie.superarchive.v2.web.identify;

public class SWIGTYPE_p_TaskContext {
  private transient long swigCPtr;

  protected SWIGTYPE_p_TaskContext(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_TaskContext() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_TaskContext obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

