/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.baidu.cie.superarchive.v2.web.identify;

public class TaskContext {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TaskContext(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TaskContext obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SearchDocModuleJNI.delete_TaskContext(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCurrentTaskId(java.math.BigInteger value) {
    SearchDocModuleJNI.TaskContext_currentTaskId_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getCurrentTaskId() {
    return SearchDocModuleJNI.TaskContext_currentTaskId_get(swigCPtr, this);
  }

  public TaskContext() {
    this(SearchDocModuleJNI.new_TaskContext(), true);
  }

}
