/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.baidu.cie.superarchive.v2.web.identify;

public class UnorderedMapUnsignedLongLongPicture extends java.util.AbstractMap<java.math.BigInteger, Picture> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UnorderedMapUnsignedLongLongPicture(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UnorderedMapUnsignedLongLongPicture obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SearchDocModuleJNI.delete_UnorderedMapUnsignedLongLongPicture(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  public int size() {
    return sizeImpl();
  }

  public boolean containsKey(Object key) {
    if (!(key instanceof java.math.BigInteger)) {
      return false;
    }

    return containsImpl((java.math.BigInteger)key);
  }

  public Picture get(Object key) {
    if (!(key instanceof java.math.BigInteger)) {
      return null;
    }

    Iterator itr = find((java.math.BigInteger) key);
    if (itr.isNot(end())) {
      return itr.getValue();
    }

    return null;
  }

  public Picture put(java.math.BigInteger key, Picture value) {
    Iterator itr = find((java.math.BigInteger) key);
    if (itr.isNot(end())) {
      Picture oldValue = itr.getValue();
      itr.setValue(value);
      return oldValue;
    } else {
      putUnchecked(key, value);
      return null;
    }
  }

  public Picture remove(Object key) {
    if (!(key instanceof java.math.BigInteger)) {
      return null;
    }

    Iterator itr = find((java.math.BigInteger) key);
    if (itr.isNot(end())) {
      Picture oldValue = itr.getValue();
      removeUnchecked(itr);
      return oldValue;
    } else {
      return null;
    }
  }

  public java.util.Set<Entry<java.math.BigInteger, Picture>> entrySet() {
    java.util.Set<Entry<java.math.BigInteger, Picture>> setToReturn =
        new java.util.HashSet<Entry<java.math.BigInteger, Picture>>();

    Iterator itr = begin();
    final Iterator end = end();
    while (itr.isNot(end)) {
      setToReturn.add(new Entry<java.math.BigInteger, Picture>() {
        private Iterator iterator;

        private Entry<java.math.BigInteger, Picture> init(Iterator iterator) {
          this.iterator = iterator;
          return this;
        }

        public java.math.BigInteger getKey() {
          return iterator.getKey();
        }

        public Picture getValue() {
          return iterator.getValue();
        }

        public Picture setValue(Picture newValue) {
          Picture oldValue = iterator.getValue();
          iterator.setValue(newValue);
          return oldValue;
        }
      }.init(itr));
      itr = itr.getNextUnchecked();
    }

    return setToReturn;
  }

  public UnorderedMapUnsignedLongLongPicture() {
    this(SearchDocModuleJNI.new_UnorderedMapUnsignedLongLongPicture__SWIG_0(), true);
  }

  public UnorderedMapUnsignedLongLongPicture(UnorderedMapUnsignedLongLongPicture other) {
    this(SearchDocModuleJNI.new_UnorderedMapUnsignedLongLongPicture__SWIG_1(
            UnorderedMapUnsignedLongLongPicture.getCPtr(other), other), true);
  }

  static protected class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;

    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }

    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }

    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }

    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SearchDocModuleJNI.delete_UnorderedMapUnsignedLongLongPicture_Iterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }

    private Iterator getNextUnchecked() {
      return new Iterator(
              SearchDocModuleJNI.UnorderedMapUnsignedLongLongPicture_Iterator_getNextUnchecked(swigCPtr, this), true);
    }

    private boolean isNot(Iterator other) {
      return SearchDocModuleJNI
              .UnorderedMapUnsignedLongLongPicture_Iterator_isNot(swigCPtr, this, Iterator.getCPtr(other), other);
    }

    private java.math.BigInteger getKey() {
      return SearchDocModuleJNI.UnorderedMapUnsignedLongLongPicture_Iterator_getKey(swigCPtr, this);
    }

    private Picture getValue() {
      return new Picture(SearchDocModuleJNI.UnorderedMapUnsignedLongLongPicture_Iterator_getValue(swigCPtr, this), true);
    }

    private void setValue(Picture newValue) {
      SearchDocModuleJNI
              .UnorderedMapUnsignedLongLongPicture_Iterator_setValue(swigCPtr, this, Picture.getCPtr(newValue), newValue);
    }

  }

  public boolean isEmpty() {
    return SearchDocModuleJNI.UnorderedMapUnsignedLongLongPicture_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SearchDocModuleJNI.UnorderedMapUnsignedLongLongPicture_clear(swigCPtr, this);
  }

  private Iterator find(java.math.BigInteger key) {
    return new Iterator(SearchDocModuleJNI.UnorderedMapUnsignedLongLongPicture_find(swigCPtr, this, key), true);
  }

  private Iterator begin() {
    return new Iterator(SearchDocModuleJNI.UnorderedMapUnsignedLongLongPicture_begin(swigCPtr, this), true);
  }

  private Iterator end() {
    return new Iterator(SearchDocModuleJNI.UnorderedMapUnsignedLongLongPicture_end(swigCPtr, this), true);
  }

  private int sizeImpl() {
    return SearchDocModuleJNI.UnorderedMapUnsignedLongLongPicture_sizeImpl(swigCPtr, this);
  }

  private boolean containsImpl(java.math.BigInteger key) {
    return SearchDocModuleJNI.UnorderedMapUnsignedLongLongPicture_containsImpl(swigCPtr, this, key);
  }

  private void putUnchecked(java.math.BigInteger key, Picture value) {
    SearchDocModuleJNI
            .UnorderedMapUnsignedLongLongPicture_putUnchecked(swigCPtr, this, key, Picture.getCPtr(value), value);
  }

  private void removeUnchecked(Iterator itr) {
    SearchDocModuleJNI.UnorderedMapUnsignedLongLongPicture_removeUnchecked(swigCPtr, this, Iterator.getCPtr(itr), itr);
  }

}
