/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.baidu.cie.superarchive.v2.web.identify;

public class UnorderedMapIntInt extends java.util.AbstractMap<Integer, Integer> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UnorderedMapIntInt(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UnorderedMapIntInt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SearchDocModuleJNI.delete_UnorderedMapIntInt(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  public int size() {
    return sizeImpl();
  }

  public boolean containsKey(Object key) {
    if (!(key instanceof Integer)) {
      return false;
    }

    return containsImpl((Integer)key);
  }

  public Integer get(Object key) {
    if (!(key instanceof Integer)) {
      return null;
    }

    Iterator itr = find((Integer) key);
    if (itr.isNot(end())) {
      return itr.getValue();
    }

    return null;
  }

  public Integer put(Integer key, Integer value) {
    Iterator itr = find((Integer) key);
    if (itr.isNot(end())) {
      Integer oldValue = itr.getValue();
      itr.setValue(value);
      return oldValue;
    } else {
      putUnchecked(key, value);
      return null;
    }
  }

  public Integer remove(Object key) {
    if (!(key instanceof Integer)) {
      return null;
    }

    Iterator itr = find((Integer) key);
    if (itr.isNot(end())) {
      Integer oldValue = itr.getValue();
      removeUnchecked(itr);
      return oldValue;
    } else {
      return null;
    }
  }

  public java.util.Set<Entry<Integer, Integer>> entrySet() {
    java.util.Set<Entry<Integer, Integer>> setToReturn =
        new java.util.HashSet<Entry<Integer, Integer>>();

    Iterator itr = begin();
    final Iterator end = end();
    while (itr.isNot(end)) {
      setToReturn.add(new Entry<Integer, Integer>() {
        private Iterator iterator;

        private Entry<Integer, Integer> init(Iterator iterator) {
          this.iterator = iterator;
          return this;
        }

        public Integer getKey() {
          return iterator.getKey();
        }

        public Integer getValue() {
          return iterator.getValue();
        }

        public Integer setValue(Integer newValue) {
          Integer oldValue = iterator.getValue();
          iterator.setValue(newValue);
          return oldValue;
        }
      }.init(itr));
      itr = itr.getNextUnchecked();
    }

    return setToReturn;
  }

  public UnorderedMapIntInt() {
    this(SearchDocModuleJNI.new_UnorderedMapIntInt__SWIG_0(), true);
  }

  public UnorderedMapIntInt(UnorderedMapIntInt other) {
    this(SearchDocModuleJNI.new_UnorderedMapIntInt__SWIG_1(UnorderedMapIntInt.getCPtr(other), other), true);
  }

  static protected class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;

    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }

    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }

    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }

    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SearchDocModuleJNI.delete_UnorderedMapIntInt_Iterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }

    private Iterator getNextUnchecked() {
      return new Iterator(SearchDocModuleJNI.UnorderedMapIntInt_Iterator_getNextUnchecked(swigCPtr, this), true);
    }

    private boolean isNot(Iterator other) {
      return SearchDocModuleJNI.UnorderedMapIntInt_Iterator_isNot(swigCPtr, this, Iterator.getCPtr(other), other);
    }

    private int getKey() {
      return SearchDocModuleJNI.UnorderedMapIntInt_Iterator_getKey(swigCPtr, this);
    }

    private int getValue() {
      return SearchDocModuleJNI.UnorderedMapIntInt_Iterator_getValue(swigCPtr, this);
    }

    private void setValue(int newValue) {
      SearchDocModuleJNI.UnorderedMapIntInt_Iterator_setValue(swigCPtr, this, newValue);
    }

  }

  public boolean isEmpty() {
    return SearchDocModuleJNI.UnorderedMapIntInt_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SearchDocModuleJNI.UnorderedMapIntInt_clear(swigCPtr, this);
  }

  private Iterator find(int key) {
    return new Iterator(SearchDocModuleJNI.UnorderedMapIntInt_find(swigCPtr, this, key), true);
  }

  private Iterator begin() {
    return new Iterator(SearchDocModuleJNI.UnorderedMapIntInt_begin(swigCPtr, this), true);
  }

  private Iterator end() {
    return new Iterator(SearchDocModuleJNI.UnorderedMapIntInt_end(swigCPtr, this), true);
  }

  private int sizeImpl() {
    return SearchDocModuleJNI.UnorderedMapIntInt_sizeImpl(swigCPtr, this);
  }

  private boolean containsImpl(int key) {
    return SearchDocModuleJNI.UnorderedMapIntInt_containsImpl(swigCPtr, this, key);
  }

  private void putUnchecked(int key, int value) {
    SearchDocModuleJNI.UnorderedMapIntInt_putUnchecked(swigCPtr, this, key, value);
  }

  private void removeUnchecked(Iterator itr) {
    SearchDocModuleJNI.UnorderedMapIntInt_removeUnchecked(swigCPtr, this, Iterator.getCPtr(itr), itr);
  }

}
