/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.baidu.cie.superarchive.v2.web.identify;

public class UnorderedMapStringString extends java.util.AbstractMap<String, String> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UnorderedMapStringString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UnorderedMapStringString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SearchDocModuleJNI.delete_UnorderedMapStringString(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  public int size() {
    return sizeImpl();
  }

  public boolean containsKey(Object key) {
    if (!(key instanceof String)) {
      return false;
    }

    return containsImpl((String)key);
  }

  public String get(Object key) {
    if (!(key instanceof String)) {
      return null;
    }

    Iterator itr = find((String) key);
    if (itr.isNot(end())) {
      return itr.getValue();
    }

    return null;
  }

  public String put(String key, String value) {
    Iterator itr = find((String) key);
    if (itr.isNot(end())) {
      String oldValue = itr.getValue();
      itr.setValue(value);
      return oldValue;
    } else {
      putUnchecked(key, value);
      return null;
    }
  }

  public String remove(Object key) {
    if (!(key instanceof String)) {
      return null;
    }

    Iterator itr = find((String) key);
    if (itr.isNot(end())) {
      String oldValue = itr.getValue();
      removeUnchecked(itr);
      return oldValue;
    } else {
      return null;
    }
  }

  public java.util.Set<Entry<String, String>> entrySet() {
    java.util.Set<Entry<String, String>> setToReturn =
        new java.util.HashSet<Entry<String, String>>();

    Iterator itr = begin();
    final Iterator end = end();
    while (itr.isNot(end)) {
      setToReturn.add(new Entry<String, String>() {
        private Iterator iterator;

        private Entry<String, String> init(Iterator iterator) {
          this.iterator = iterator;
          return this;
        }

        public String getKey() {
          return iterator.getKey();
        }

        public String getValue() {
          return iterator.getValue();
        }

        public String setValue(String newValue) {
          String oldValue = iterator.getValue();
          iterator.setValue(newValue);
          return oldValue;
        }
      }.init(itr));
      itr = itr.getNextUnchecked();
    }

    return setToReturn;
  }

  public UnorderedMapStringString() {
    this(SearchDocModuleJNI.new_UnorderedMapStringString__SWIG_0(), true);
  }

  public UnorderedMapStringString(UnorderedMapStringString other) {
    this(SearchDocModuleJNI.new_UnorderedMapStringString__SWIG_1(UnorderedMapStringString.getCPtr(other), other), true);
  }

  static protected class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;

    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }

    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }

    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }

    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SearchDocModuleJNI.delete_UnorderedMapStringString_Iterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }

    private Iterator getNextUnchecked() {
      return new Iterator(SearchDocModuleJNI.UnorderedMapStringString_Iterator_getNextUnchecked(swigCPtr, this), true);
    }

    private boolean isNot(Iterator other) {
      return SearchDocModuleJNI.UnorderedMapStringString_Iterator_isNot(swigCPtr, this, Iterator.getCPtr(other), other);
    }

    private String getKey() {
      return SearchDocModuleJNI.UnorderedMapStringString_Iterator_getKey(swigCPtr, this);
    }

    private String getValue() {
      return SearchDocModuleJNI.UnorderedMapStringString_Iterator_getValue(swigCPtr, this);
    }

    private void setValue(String newValue) {
      SearchDocModuleJNI.UnorderedMapStringString_Iterator_setValue(swigCPtr, this, newValue);
    }

  }

  public boolean isEmpty() {
    return SearchDocModuleJNI.UnorderedMapStringString_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SearchDocModuleJNI.UnorderedMapStringString_clear(swigCPtr, this);
  }

  private Iterator find(String key) {
    return new Iterator(SearchDocModuleJNI.UnorderedMapStringString_find(swigCPtr, this, key), true);
  }

  private Iterator begin() {
    return new Iterator(SearchDocModuleJNI.UnorderedMapStringString_begin(swigCPtr, this), true);
  }

  private Iterator end() {
    return new Iterator(SearchDocModuleJNI.UnorderedMapStringString_end(swigCPtr, this), true);
  }

  private int sizeImpl() {
    return SearchDocModuleJNI.UnorderedMapStringString_sizeImpl(swigCPtr, this);
  }

  private boolean containsImpl(String key) {
    return SearchDocModuleJNI.UnorderedMapStringString_containsImpl(swigCPtr, this, key);
  }

  private void putUnchecked(String key, String value) {
    SearchDocModuleJNI.UnorderedMapStringString_putUnchecked(swigCPtr, this, key, value);
  }

  private void removeUnchecked(Iterator itr) {
    SearchDocModuleJNI.UnorderedMapStringString_removeUnchecked(swigCPtr, this, Iterator.getCPtr(itr), itr);
  }

}
