/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.baidu.cie.superarchive.v2.web.identify;

public class VecCluster extends java.util.AbstractList<Cluster> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VecCluster(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VecCluster obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SearchDocModuleJNI.delete_VecCluster(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VecCluster(Cluster[] initialElements) {
    this();
    reserve(initialElements.length);

    for (Cluster element : initialElements) {
      add(element);
    }
  }

  public VecCluster(Iterable<Cluster> initialElements) {
    this();
    for (Cluster element : initialElements) {
      add(element);
    }
  }

  public Cluster get(int index) {
    return doGet(index);
  }

  public Cluster set(int index, Cluster e) {
    return doSet(index, e);
  }

  public boolean add(Cluster e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Cluster e) {
    modCount++;
    doAdd(index, e);
  }

  public Cluster remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public VecCluster() {
    this(SearchDocModuleJNI.new_VecCluster__SWIG_0(), true);
  }

  public VecCluster(VecCluster other) {
    this(SearchDocModuleJNI.new_VecCluster__SWIG_1(VecCluster.getCPtr(other), other), true);
  }

  public long capacity() {
    return SearchDocModuleJNI.VecCluster_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    SearchDocModuleJNI.VecCluster_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return SearchDocModuleJNI.VecCluster_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SearchDocModuleJNI.VecCluster_clear(swigCPtr, this);
  }

  public VecCluster(int count, Cluster value) {
    this(SearchDocModuleJNI.new_VecCluster__SWIG_2(count, Cluster.getCPtr(value), value), true);
  }

  private int doSize() {
    return SearchDocModuleJNI.VecCluster_doSize(swigCPtr, this);
  }

  private void doAdd(Cluster x) {
    SearchDocModuleJNI.VecCluster_doAdd__SWIG_0(swigCPtr, this, Cluster.getCPtr(x), x);
  }

  private void doAdd(int index, Cluster x) {
    SearchDocModuleJNI.VecCluster_doAdd__SWIG_1(swigCPtr, this, index, Cluster.getCPtr(x), x);
  }

  private Cluster doRemove(int index) {
    return new Cluster(SearchDocModuleJNI.VecCluster_doRemove(swigCPtr, this, index), true);
  }

  private Cluster doGet(int index) {
    return new Cluster(SearchDocModuleJNI.VecCluster_doGet(swigCPtr, this, index), false);
  }

  private Cluster doSet(int index, Cluster val) {
    return new Cluster(SearchDocModuleJNI.VecCluster_doSet(swigCPtr, this, index, Cluster.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    SearchDocModuleJNI.VecCluster_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
