/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.baidu.cie.superarchive.v2.web.identify;

public class VecConnectPair extends java.util.AbstractList<ConnectPair> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VecConnectPair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VecConnectPair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SearchDocModuleJNI.delete_VecConnectPair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VecConnectPair(ConnectPair[] initialElements) {
    this();
    reserve(initialElements.length);

    for (ConnectPair element : initialElements) {
      add(element);
    }
  }

  public VecConnectPair(Iterable<ConnectPair> initialElements) {
    this();
    for (ConnectPair element : initialElements) {
      add(element);
    }
  }

  public ConnectPair get(int index) {
    return doGet(index);
  }

  public ConnectPair set(int index, ConnectPair e) {
    return doSet(index, e);
  }

  public boolean add(ConnectPair e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, ConnectPair e) {
    modCount++;
    doAdd(index, e);
  }

  public ConnectPair remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public VecConnectPair() {
    this(SearchDocModuleJNI.new_VecConnectPair__SWIG_0(), true);
  }

  public VecConnectPair(VecConnectPair other) {
    this(SearchDocModuleJNI.new_VecConnectPair__SWIG_1(VecConnectPair.getCPtr(other), other), true);
  }

  public long capacity() {
    return SearchDocModuleJNI.VecConnectPair_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    SearchDocModuleJNI.VecConnectPair_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return SearchDocModuleJNI.VecConnectPair_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SearchDocModuleJNI.VecConnectPair_clear(swigCPtr, this);
  }

  public VecConnectPair(int count, ConnectPair value) {
    this(SearchDocModuleJNI.new_VecConnectPair__SWIG_2(count, ConnectPair.getCPtr(value), value), true);
  }

  private int doSize() {
    return SearchDocModuleJNI.VecConnectPair_doSize(swigCPtr, this);
  }

  private void doAdd(ConnectPair x) {
    SearchDocModuleJNI.VecConnectPair_doAdd__SWIG_0(swigCPtr, this, ConnectPair.getCPtr(x), x);
  }

  private void doAdd(int index, ConnectPair x) {
    SearchDocModuleJNI.VecConnectPair_doAdd__SWIG_1(swigCPtr, this, index, ConnectPair.getCPtr(x), x);
  }

  private ConnectPair doRemove(int index) {
    return new ConnectPair(SearchDocModuleJNI.VecConnectPair_doRemove(swigCPtr, this, index), true);
  }

  private ConnectPair doGet(int index) {
    return new ConnectPair(SearchDocModuleJNI.VecConnectPair_doGet(swigCPtr, this, index), false);
  }

  private ConnectPair doSet(int index, ConnectPair val) {
    return new ConnectPair(SearchDocModuleJNI.VecConnectPair_doSet(swigCPtr, this, index, ConnectPair.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    SearchDocModuleJNI.VecConnectPair_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
