/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.baidu.cie.superarchive.v2.web.identify;

public class VecDocument extends java.util.AbstractList<Document> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VecDocument(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VecDocument obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SearchDocModuleJNI.delete_VecDocument(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VecDocument(Document[] initialElements) {
    this();
    reserve(initialElements.length);

    for (Document element : initialElements) {
      add(element);
    }
  }

  public VecDocument(Iterable<Document> initialElements) {
    this();
    for (Document element : initialElements) {
      add(element);
    }
  }

  public Document get(int index) {
    return doGet(index);
  }

  public Document set(int index, Document e) {
    return doSet(index, e);
  }

  public boolean add(Document e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Document e) {
    modCount++;
    doAdd(index, e);
  }

  public Document remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public VecDocument() {
    this(SearchDocModuleJNI.new_VecDocument__SWIG_0(), true);
  }

  public VecDocument(VecDocument other) {
    this(SearchDocModuleJNI.new_VecDocument__SWIG_1(VecDocument.getCPtr(other), other), true);
  }

  public long capacity() {
    return SearchDocModuleJNI.VecDocument_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    SearchDocModuleJNI.VecDocument_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return SearchDocModuleJNI.VecDocument_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SearchDocModuleJNI.VecDocument_clear(swigCPtr, this);
  }

  public VecDocument(int count, Document value) {
    this(SearchDocModuleJNI.new_VecDocument__SWIG_2(count, Document.getCPtr(value), value), true);
  }

  private int doSize() {
    return SearchDocModuleJNI.VecDocument_doSize(swigCPtr, this);
  }

  private void doAdd(Document x) {
    SearchDocModuleJNI.VecDocument_doAdd__SWIG_0(swigCPtr, this, Document.getCPtr(x), x);
  }

  private void doAdd(int index, Document x) {
    SearchDocModuleJNI.VecDocument_doAdd__SWIG_1(swigCPtr, this, index, Document.getCPtr(x), x);
  }

  private Document doRemove(int index) {
    return new Document(SearchDocModuleJNI.VecDocument_doRemove(swigCPtr, this, index), true);
  }

  private Document doGet(int index) {
    return new Document(SearchDocModuleJNI.VecDocument_doGet(swigCPtr, this, index), false);
  }

  private Document doSet(int index, Document val) {
    return new Document(SearchDocModuleJNI.VecDocument_doSet(swigCPtr, this, index, Document.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    SearchDocModuleJNI.VecDocument_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
