/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.baidu.cie.superarchive.v2.web.identify;

public class VecLongLong extends java.util.AbstractList<Long> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VecLongLong(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VecLongLong obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SearchDocModuleJNI.delete_VecLongLong(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VecLongLong(long[] initialElements) {
    this();
    reserve(initialElements.length);

    for (long element : initialElements) {
      add(element);
    }
  }

  public VecLongLong(Iterable<Long> initialElements) {
    this();
    for (long element : initialElements) {
      add(element);
    }
  }

  public Long get(int index) {
    return doGet(index);
  }

  public Long set(int index, Long e) {
    return doSet(index, e);
  }

  public boolean add(Long e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Long e) {
    modCount++;
    doAdd(index, e);
  }

  public Long remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public VecLongLong() {
    this(SearchDocModuleJNI.new_VecLongLong__SWIG_0(), true);
  }

  public VecLongLong(VecLongLong other) {
    this(SearchDocModuleJNI.new_VecLongLong__SWIG_1(VecLongLong.getCPtr(other), other), true);
  }

  public long capacity() {
    return SearchDocModuleJNI.VecLongLong_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    SearchDocModuleJNI.VecLongLong_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return SearchDocModuleJNI.VecLongLong_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SearchDocModuleJNI.VecLongLong_clear(swigCPtr, this);
  }

  public VecLongLong(int count, long value) {
    this(SearchDocModuleJNI.new_VecLongLong__SWIG_2(count, value), true);
  }

  private int doSize() {
    return SearchDocModuleJNI.VecLongLong_doSize(swigCPtr, this);
  }

  private void doAdd(long x) {
    SearchDocModuleJNI.VecLongLong_doAdd__SWIG_0(swigCPtr, this, x);
  }

  private void doAdd(int index, long x) {
    SearchDocModuleJNI.VecLongLong_doAdd__SWIG_1(swigCPtr, this, index, x);
  }

  private long doRemove(int index) {
    return SearchDocModuleJNI.VecLongLong_doRemove(swigCPtr, this, index);
  }

  private long doGet(int index) {
    return SearchDocModuleJNI.VecLongLong_doGet(swigCPtr, this, index);
  }

  private long doSet(int index, long val) {
    return SearchDocModuleJNI.VecLongLong_doSet(swigCPtr, this, index, val);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    SearchDocModuleJNI.VecLongLong_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
