/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.baidu.cie.superarchive.v2.web.identify;

public class VecPicture extends java.util.AbstractList<Picture> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VecPicture(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VecPicture obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SearchDocModuleJNI.delete_VecPicture(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VecPicture(Picture[] initialElements) {
    this();
    reserve(initialElements.length);

    for (Picture element : initialElements) {
      add(element);
    }
  }

  public VecPicture(Iterable<Picture> initialElements) {
    this();
    for (Picture element : initialElements) {
      add(element);
    }
  }

  public Picture get(int index) {
    return doGet(index);
  }

  public Picture set(int index, Picture e) {
    return doSet(index, e);
  }

  public boolean add(Picture e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Picture e) {
    modCount++;
    doAdd(index, e);
  }

  public Picture remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public VecPicture() {
    this(SearchDocModuleJNI.new_VecPicture__SWIG_0(), true);
  }

  public VecPicture(VecPicture other) {
    this(SearchDocModuleJNI.new_VecPicture__SWIG_1(VecPicture.getCPtr(other), other), true);
  }

  public long capacity() {
    return SearchDocModuleJNI.VecPicture_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    SearchDocModuleJNI.VecPicture_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return SearchDocModuleJNI.VecPicture_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SearchDocModuleJNI.VecPicture_clear(swigCPtr, this);
  }

  public VecPicture(int count, Picture value) {
    this(SearchDocModuleJNI.new_VecPicture__SWIG_2(count, Picture.getCPtr(value), value), true);
  }

  private int doSize() {
    return SearchDocModuleJNI.VecPicture_doSize(swigCPtr, this);
  }

  private void doAdd(Picture x) {
    SearchDocModuleJNI.VecPicture_doAdd__SWIG_0(swigCPtr, this, Picture.getCPtr(x), x);
  }

  private void doAdd(int index, Picture x) {
    SearchDocModuleJNI.VecPicture_doAdd__SWIG_1(swigCPtr, this, index, Picture.getCPtr(x), x);
  }

  private Picture doRemove(int index) {
    return new Picture(SearchDocModuleJNI.VecPicture_doRemove(swigCPtr, this, index), true);
  }

  private Picture doGet(int index) {
    return new Picture(SearchDocModuleJNI.VecPicture_doGet(swigCPtr, this, index), false);
  }

  private Picture doSet(int index, Picture val) {
    return new Picture(SearchDocModuleJNI.VecPicture_doSet(swigCPtr, this, index, Picture.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    SearchDocModuleJNI.VecPicture_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
