/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.baidu.cie.superarchive.v2.web.identify;

public class VecQueryResult extends java.util.AbstractList<QueryResult> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VecQueryResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VecQueryResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SearchDocModuleJNI.delete_VecQueryResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VecQueryResult(QueryResult[] initialElements) {
    this();
    reserve(initialElements.length);

    for (QueryResult element : initialElements) {
      add(element);
    }
  }

  public VecQueryResult(Iterable<QueryResult> initialElements) {
    this();
    for (QueryResult element : initialElements) {
      add(element);
    }
  }

  public QueryResult get(int index) {
    return doGet(index);
  }

  public QueryResult set(int index, QueryResult e) {
    return doSet(index, e);
  }

  public boolean add(QueryResult e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, QueryResult e) {
    modCount++;
    doAdd(index, e);
  }

  public QueryResult remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public VecQueryResult() {
    this(SearchDocModuleJNI.new_VecQueryResult__SWIG_0(), true);
  }

  public VecQueryResult(VecQueryResult other) {
    this(SearchDocModuleJNI.new_VecQueryResult__SWIG_1(VecQueryResult.getCPtr(other), other), true);
  }

  public long capacity() {
    return SearchDocModuleJNI.VecQueryResult_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    SearchDocModuleJNI.VecQueryResult_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return SearchDocModuleJNI.VecQueryResult_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SearchDocModuleJNI.VecQueryResult_clear(swigCPtr, this);
  }

  public VecQueryResult(int count, QueryResult value) {
    this(SearchDocModuleJNI.new_VecQueryResult__SWIG_2(count, QueryResult.getCPtr(value), value), true);
  }

  private int doSize() {
    return SearchDocModuleJNI.VecQueryResult_doSize(swigCPtr, this);
  }

  private void doAdd(QueryResult x) {
    SearchDocModuleJNI.VecQueryResult_doAdd__SWIG_0(swigCPtr, this, QueryResult.getCPtr(x), x);
  }

  private void doAdd(int index, QueryResult x) {
    SearchDocModuleJNI.VecQueryResult_doAdd__SWIG_1(swigCPtr, this, index, QueryResult.getCPtr(x), x);
  }

  private QueryResult doRemove(int index) {
    return new QueryResult(SearchDocModuleJNI.VecQueryResult_doRemove(swigCPtr, this, index), true);
  }

  private QueryResult doGet(int index) {
    return new QueryResult(SearchDocModuleJNI.VecQueryResult_doGet(swigCPtr, this, index), false);
  }

  private QueryResult doSet(int index, QueryResult val) {
    return new QueryResult(SearchDocModuleJNI.VecQueryResult_doSet(swigCPtr, this, index, QueryResult.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    SearchDocModuleJNI.VecQueryResult_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
