/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.baidu.cie.superarchive.v2.web.identify;

public class VecVecConnectDocInfo extends java.util.AbstractList<VecConnectDocInfo> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VecVecConnectDocInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VecVecConnectDocInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SearchDocModuleJNI.delete_VecVecConnectDocInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VecVecConnectDocInfo(VecConnectDocInfo[] initialElements) {
    this();
    reserve(initialElements.length);

    for (VecConnectDocInfo element : initialElements) {
      add(element);
    }
  }

  public VecVecConnectDocInfo(Iterable<VecConnectDocInfo> initialElements) {
    this();
    for (VecConnectDocInfo element : initialElements) {
      add(element);
    }
  }

  public VecConnectDocInfo get(int index) {
    return doGet(index);
  }

  public VecConnectDocInfo set(int index, VecConnectDocInfo e) {
    return doSet(index, e);
  }

  public boolean add(VecConnectDocInfo e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, VecConnectDocInfo e) {
    modCount++;
    doAdd(index, e);
  }

  public VecConnectDocInfo remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public VecVecConnectDocInfo() {
    this(SearchDocModuleJNI.new_VecVecConnectDocInfo__SWIG_0(), true);
  }

  public VecVecConnectDocInfo(VecVecConnectDocInfo other) {
    this(SearchDocModuleJNI.new_VecVecConnectDocInfo__SWIG_1(VecVecConnectDocInfo.getCPtr(other), other), true);
  }

  public long capacity() {
    return SearchDocModuleJNI.VecVecConnectDocInfo_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    SearchDocModuleJNI.VecVecConnectDocInfo_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return SearchDocModuleJNI.VecVecConnectDocInfo_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SearchDocModuleJNI.VecVecConnectDocInfo_clear(swigCPtr, this);
  }

  public VecVecConnectDocInfo(int count, VecConnectDocInfo value) {
    this(SearchDocModuleJNI.new_VecVecConnectDocInfo__SWIG_2(count, VecConnectDocInfo.getCPtr(value), value), true);
  }

  private int doSize() {
    return SearchDocModuleJNI.VecVecConnectDocInfo_doSize(swigCPtr, this);
  }

  private void doAdd(VecConnectDocInfo x) {
    SearchDocModuleJNI.VecVecConnectDocInfo_doAdd__SWIG_0(swigCPtr, this, VecConnectDocInfo.getCPtr(x), x);
  }

  private void doAdd(int index, VecConnectDocInfo x) {
    SearchDocModuleJNI.VecVecConnectDocInfo_doAdd__SWIG_1(swigCPtr, this, index, VecConnectDocInfo.getCPtr(x), x);
  }

  private VecConnectDocInfo doRemove(int index) {
    return new VecConnectDocInfo(SearchDocModuleJNI.VecVecConnectDocInfo_doRemove(swigCPtr, this, index), true);
  }

  private VecConnectDocInfo doGet(int index) {
    return new VecConnectDocInfo(SearchDocModuleJNI.VecVecConnectDocInfo_doGet(swigCPtr, this, index), false);
  }

  private VecConnectDocInfo doSet(int index, VecConnectDocInfo val) {
    return new VecConnectDocInfo(
            SearchDocModuleJNI.VecVecConnectDocInfo_doSet(swigCPtr, this, index, VecConnectDocInfo.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    SearchDocModuleJNI.VecVecConnectDocInfo_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
