/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.baidu.cie.superarchive.v2.web.identify;

public class VecVecPicture extends java.util.AbstractList<VecPicture> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VecVecPicture(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VecVecPicture obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SearchDocModuleJNI.delete_VecVecPicture(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VecVecPicture(VecPicture[] initialElements) {
    this();
    reserve(initialElements.length);

    for (VecPicture element : initialElements) {
      add(element);
    }
  }

  public VecVecPicture(Iterable<VecPicture> initialElements) {
    this();
    for (VecPicture element : initialElements) {
      add(element);
    }
  }

  public VecPicture get(int index) {
    return doGet(index);
  }

  public VecPicture set(int index, VecPicture e) {
    return doSet(index, e);
  }

  public boolean add(VecPicture e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, VecPicture e) {
    modCount++;
    doAdd(index, e);
  }

  public VecPicture remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public VecVecPicture() {
    this(SearchDocModuleJNI.new_VecVecPicture__SWIG_0(), true);
  }

  public VecVecPicture(VecVecPicture other) {
    this(SearchDocModuleJNI.new_VecVecPicture__SWIG_1(VecVecPicture.getCPtr(other), other), true);
  }

  public long capacity() {
    return SearchDocModuleJNI.VecVecPicture_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    SearchDocModuleJNI.VecVecPicture_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return SearchDocModuleJNI.VecVecPicture_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SearchDocModuleJNI.VecVecPicture_clear(swigCPtr, this);
  }

  public VecVecPicture(int count, VecPicture value) {
    this(SearchDocModuleJNI.new_VecVecPicture__SWIG_2(count, VecPicture.getCPtr(value), value), true);
  }

  private int doSize() {
    return SearchDocModuleJNI.VecVecPicture_doSize(swigCPtr, this);
  }

  private void doAdd(VecPicture x) {
    SearchDocModuleJNI.VecVecPicture_doAdd__SWIG_0(swigCPtr, this, VecPicture.getCPtr(x), x);
  }

  private void doAdd(int index, VecPicture x) {
    SearchDocModuleJNI.VecVecPicture_doAdd__SWIG_1(swigCPtr, this, index, VecPicture.getCPtr(x), x);
  }

  private VecPicture doRemove(int index) {
    return new VecPicture(SearchDocModuleJNI.VecVecPicture_doRemove(swigCPtr, this, index), true);
  }

  private VecPicture doGet(int index) {
    return new VecPicture(SearchDocModuleJNI.VecVecPicture_doGet(swigCPtr, this, index), false);
  }

  private VecPicture doSet(int index, VecPicture val) {
    return new VecPicture(SearchDocModuleJNI.VecVecPicture_doSet(swigCPtr, this, index, VecPicture.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    SearchDocModuleJNI.VecVecPicture_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
