spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://yq01-aip-gpu-test16.yq01:8306/superarchivev2_1?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    url: jdbc:mysql://yq01-aip-gpu-test20.yq01:8310/superarchivev2?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
#    url: jdbc:mysql://yq01-aip-gpu-test20.yq01:8307/superarchivev2?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
#    url: jdbc:mysql://yq01-aip-gpu-test20.yq01:8309/superarchivev2?autoReconnect=true&useSSL=false
    username: root
    password: baidu@123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 2
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 300000
      pool-name: DatabookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
#      connection-test-query: SELECT 1
      connection-init-sql: set names utf8
  jpa:

    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    show-sql: true