/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lp_jni_hello_HelloJNI */

#ifndef _Included_lp_jni_hello_HelloJNI
#define _Included_lp_jni_hello_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lp_jni_hello_HelloJNI
 * Method:    hello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_lp_jni_hello_HelloJNI_hello
  (JNIEnv *, jobject, jstring);

/*
 * Class:     lp_jni_hello_HelloJNI
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_lp_jni_hello_HelloJNI_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
